/* insert into utilities values ('Academy Catalog Data Generator'); */
insert into utilities values ('Bazaar Voice Product Feed Generator');
insert into utilities values ('Booster Questions Learner Notifications');
insert into utilities values ('CE Broker Upload');
insert into utilities values ('CE Quick Training Alerts');
insert into utilities values ('Course Changes Admin Email');
insert into utilities values ('Course Enrollment Instructor Emails');
insert into utilities values ('Course Enrollment Learner Emails');
insert into utilities values ('Course Enrollment Supervisor Emails');
insert into utilities values ('Course Session Attendances Emails');
insert into utilities values ('Course Session Reminder Emails');
insert into utilities values ('Course Swap');
insert into utilities values ('Data Export');
insert into utilities values ('Document Edit Alert Editors Emails');
insert into utilities values ('Document Edit Alert Owner Emails');
insert into utilities values ('Document Edit Alert Owners Emails');
insert into utilities values ('Document Revision Date Alert Emails');
insert into utilities values ('Document Warning Learner Emails');
insert into utilities values ('External Course Enrollments Pending Email');
/* insert into utilities values ('File Import'); */
insert into utilities values ('Game Leaderboard Calculations');
insert into utilities values ('License and Certification Reminder Emails');
insert into utilities values ('Manual Warning Emails');
insert into utilities values ('Process Auto Enrollment Queue Record');
insert into utilities values ('Process Course Enrollment Queue');
insert into utilities values ('Process Course Swap Queue Record');
insert into utilities values ('Process Curriculum Enrollment Queue');
insert into utilities values ('Queue Course Warning Emails');
insert into utilities values ('Queue Courses to Swap');
insert into utilities values ('Queue Scheduled Report Emails');
insert into utilities values ('Recorded Performance Review Emails');
insert into utilities values ('Requirements Tracker Emails');
insert into utilities values ('SCORM PowerPoint Coverter');
insert into utilities values ('Send Learner Course Warning Emails');
insert into utilities values ('Send Push Notifications for Course Warning Emails');
insert into utilities values ('Send Scheduled Report Emails');
insert into utilities values ('Send Supervisor Course Warning Emails');
insert into utilities values ('SFTP Helper');
insert into utilities values ('Streaming Media Conversion Failure Email');
insert into utilities values ('Streaming Media Delete from Vimeo');
insert into utilities values ('Training Plan Enrollment Close');
insert into utilities values ('Vimeo Quota Email');
insert into utilities values ('Win SCP');